apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubia
  selector:
    app: kubia
spec:
  replicas: 3
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
      - image: luksa/kubia:v1
        name: nodejs
